//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fightxweb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cart
    {
        public int cartID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> CartStatusID { get; set; }
    
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
